Repository zdnscloud/singlecloud-ui, pull requests merged in 2020-02, with the labels that each got.

#124 fix bug#393
  packages/ui/app/containers/ClustersPage/CreatePage.js
  packages/ui/app/containers/ClustersPage/NodeViewDialog.js
Labels: bug

#125 Add docs of pull request
  docs/SUMMARY.md
Labels: need-test

#126 add pull request workflow
  docs/SUMMARY.md
  docs/dev/pull-request.md
Labels: need-review

#129 optimize tap performance
  packages/com/src/throttleRender.js
  packages/ui/app/containers/SvcMeshTapPage/Table.js
  packages/ui/app/containers/SvcMeshTapPage/tableSchema.js
Labels: optimize
